name: Build and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build for macOS (arm64)
      run: dotnet build --configuration Release --runtime osx-arm64 --no-restore
      working-directory: azq

    - name: Publish
      run: dotnet publish --configuration Release --runtime osx-arm64 --no-build --output ./publish/osx-arm64
      working-directory: azq

    - name: Zip macOS (arm64) publish
      run: zip -r publish/osx-arm64.zip publish/osx-arm64
      working-directory: azq

    - name: Build for Windows (x64)
      run: dotnet build --configuration Release --runtime win-x64 --no-restore
      working-directory: azq

    - name: Publish for Windows (x64)
      run: dotnet publish --configuration Release --runtime win-x64 --no-build --output ./publish/win-x64
      working-directory: azq

    - name: Zip Windows (x64) publish
      run: zip -r publish/win-x64.zip publish/win-x64
      working-directory: azq

    - name: Create and Upload Release 
      uses: softprops/action-gh-release@v2
      with: 
        files: |
          ./azq/publish/osx-arm64.zip
          ./azq/publish/win-x64.zip
        tag_name: v1.0.0
        release_name: Release v1.0.0 
        draft: false 
        prerelease: true
