name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish --configuration Release --no-build --output ./publish

    - name: Create and Upload Release 
      uses: softprops/action-gh-release@v2 
      with: 
        files: ./publish/** 
        tag_name: ${{ github.ref }} 
        release_name: Release ${{ github.ref }} 
        draft: false 
        prerelease: true
